topthree/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('register/', views.register_user, name = 'register'),
    path('profile/<str:username>', views.details_user, name = 'details'),
    path('delete/poll/<int:poll_id>', views.delete_poll, name ='delete_poll'),
]

topthree/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('list/', views.poll_list, name = 'list'),
    path('add/', views.add_poll, name = 'add'),
    path('edit/<int:poll_id>/choice/add', views.add_choice, name = 'add_choice'),
    path('details/<int:poll_id>', views.poll_detail, name = 'details'),
    path('details/<int:poll_id>/vote', views.poll_vote, name = 'vote'),
]

topthree/topthree/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

topthree/templates/about.html
{% extends 'base.html' %}
{% load static %}
  {% block custom_title %}
    <title>About | Top Three</title>
  {% endblock %}
  {% block custom_css %}
      <link rel="stylesheet" type = 'text/css' href="{% static 'css/about_styles.css' %}">
  {% endblock %}
{% block content %}

<body>
 <section id="about">
   <div class="container">
     <div class="row">
     <div class="col-md-5">
       <div class="about-img">
             <img class="man" src="{% static 'img/face.jpeg' %}" alt="">
       </div>
     </div>
     <br>
     <div class="col-md-7 about-right">

       <h2 class="color-3"><b>ABOUT TOPTHREE</b></h2>
       <p class="p-first">
         TopThree is an online Polling Web Applications. It allows users to create polls and vote on existing items.
            Setup your account and see whats trending in fields which interests you! You may add as many polls and choices as you want,
          but you cannot edit polls/choices.You may report about a poll using the contact page.
       </p>
       <p>
        Upcoming feature : Create private polls for your University/Workspace!
       </p>
       <br>
       <h2 class="color-3"><b>ABOUT ME</b></h2>
       <p class="p-first">
         I’m Ayush, 4th year CS Undergraduate at Heritage Institute Of Technology, Kolkata (India).
           I love the adrenaline rush of competitive coding.
           I am also a freelance graphic designer, curious about exploring new possibilities.

       </p>
       <p>
         Algorithms and Data Structures are my prime focus along with parties and rock concerts.
         I am a self-motivated musician and have mastered instruments like - guitar, drums & piano.
       </p>
       <ul class="about-link">
         <li><a href="https://iamayush.me" class="icon-button globe" target="_blank"><i class="fas fa-globe"></i></a></li>
         <li><a href="https://www.linkedin.com/in/ayushagarwal28/" class="icon-button linkedin" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
         <li><a href="https://www.facebook.com/simplyayush28" class="icon-button facebook" target="_blank"><i class="fab fa-facebook-f"></i></i></a></li>
         <li><a href="https://www.youtube.com/acoustichead" class="icon-button google-plus" target="_blank"><i class="fab fa-youtube"></i></a></li>
       </ul>
     </div>
     </div>
   </div>
   </section




{% endblock %}

topthree/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% block custom_title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    {% block custom_css %} {% endblock %}
    <script src="https://kit.fontawesome.com/9304d5c7bd.js" crossorigin="anonymous"></script>
    <style>
      body {
        font-family: 'Roboto', sans-serif;
        background-color: #fff
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">TopThree</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'polls:list' %}">Polls</a>
          <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
          <a class="nav-item nav-link" href="{% url 'contact' %}">Contact</a>
        </div>
      </div>
      {% if request.user.is_authenticated %}
        Howdy Dowdy,&nbsp&nbsp <strong><a href="{% url 'accounts:details' request.user %}">@{{request.user}}</a></strong>!
        <a class="p-2 text-dark" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i>&nbspLogout</a>
      {% else %}
        <a class="p-2 text-dark" href="{% url 'accounts:login' %}">Sign In</a>
        <a class="p-2 text-dark" href="{% url 'accounts:register' %}">Sign Up</a>
      {% endif %}
    </nav>
    {% block content %}

    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

topthree/templates/contact.html
{% extends 'base.html' %}
  {% load static %}
      {% block custom_css %}
          <link rel="stylesheet" type = 'text/css' href="{% static 'css/log_styles.css' %}">
      {% endblock %}
    {% block custom_title %}
        <title>Contact | Top Three</title>
    {% endblock %}

    {% block content %}
      <div class="container">
        <div class="row">
          <div class="col-md-6 offset-md-3">
            <h1 class="text-center">CONTACT US</h1>
            <form class="form-signin" action="" method="POST">
              {% csrf_token %}
              {% for field in form%}
                <div class="form-label-group">
                  {{ field.errors }}
                  {{ field }}
                  {{ field.label_tag }}
                </div>
              {% endfor %}
              <div class="text-center">
                <input type="submit" value="Send" class="btn btn-info btn-lg">
              </div>

            </form>
          </div>
        </div>
      </div>
    {% endblock %}

topthree/templates/home.html
{% extends 'base.html' %}
  {% load static %}
  {% block custom_title %}
    <title>Home | Top Three</title>
  {% endblock %}
  {% block custom_css %}
    <link rel="stylesheet" type = 'text/css' href="{% static 'css/home_styles.css' %}">
  {% endblock %}
  {% block content %}

  <div class="container">
    <div class="row">
      <div class="col">
        <div id="home-content">
          <h1>Vote For Your Favourite!</h1>
          <h3>Your Voice Matters!</h3>
          <hr>
          <a href="{% url 'polls:list' %}"><button type="button" class="btn btn-info btn-lg">Get Started!</button></a>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}