topthree/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('list/', views.poll_list, name = 'list'),
    path('add/', views.add_poll, name = 'add'),
    path('edit/<int:poll_id>/choice/add', views.add_choice, name = 'add_choice'),
    path('details/<int:poll_id>', views.poll_detail, name = 'details'),
    path('details/<int:poll_id>/vote', views.poll_vote, name = 'vote'),
]

topthree/topthree/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

topthree/polls/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length = 255)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.email


class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete = models.CASCADE, default = 1)
    text = models.CharField(max_length = 255)
    pub_date = models.DateField()

    def __str__(self):
        return self.text

    def user_can_vote(self, user):
        qs = user.vote_set.filter(poll = self)
        if qs.exists():
            return False
        else:
            return True

    @property
    def num_of_votes(self):
        return self.vote_set.count()


    def get_results_dict(self):
        res = []
        for choice in self.choice_set.all():
            d = {}
            d['text'] = choice.choice_text
            d['num_votes'] = choice.num_of_votes
            if not self.num_of_votes:
                d['percentage'] = 0
            else:
                d['percentage'] = round(choice.num_of_votes / self.num_of_votes * 100, 2)
            res.append(d)
        res = sorted(res, key = lambda i: (i['percentage']), reverse = True)
        return res

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 255)

    def __str__(self):
        return "{} - {}".format(self.poll.text[:25], self.choice_text[:25])

    @property
    def num_of_votes(self):
        return self.vote_set.count()

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete = models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete = models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.poll.text[:25], self.user)

topthree/polls/forms.py
from django import forms
from .models import Poll, Choice

class PollForm(forms.ModelForm):
    choice = forms.CharField(max_length = 100,
                               label = 'Choice 1',
                               min_length = 1,
                               widget = forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Player Unknown\'s Battle Grounds - PUBG'}))

    choice1 = forms.CharField(max_length = 100,
                               label = 'Choice 2',
                               min_length = 1,
                               widget = forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Call Of Duty - COD'}))

    choice2 = forms.CharField(max_length = 100,
                               label = 'Choice 3',
                               min_length = 1,
                               widget = forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Getting Over It!'}))

    class Meta:
        model = Poll
        fields = ['text',]
        widgets = {
            'text' : forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Top 3 2019 PC Games'})
        }


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']
        widgets = {
            'choice_text' : forms.TextInput(attrs = {'class' : 'form-control', 'placeholder' : 'Add your choice'})
        }

topthree/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import Poll, Choice, Vote
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .forms import PollForm, ChoiceForm
import datetime
from django.db.models import Count
# Create your views here.


def poll_list(request):
    polls = Poll.objects.all();

    if 'sort-a-z' in request.GET:
        print("This is from sort-a-z")
        polls = polls.order_by('text')

    if 'date' in request.GET:
        print("This is from date")
        polls = polls.order_by('-pub_date')

    if 'votes' in request.GET:
        polls = polls.annotate(Count('vote')).order_by('-vote__count')


    paginator = paginator = Paginator(polls, 5)
    page = request.GET.get('page')
    polls = paginator.get_page(page)

    get_dict_copy = request.GET.copy()
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()

    context = {'polls' : polls, 'params': params}
    return render(request, 'polls/poll_list.html', context)

@login_required
def poll_detail(request, poll_id):
    poll = get_object_or_404(Poll, id = poll_id)
    user_can_vote = poll.user_can_vote(request.user)

    context = {'poll' : poll}
    if user_can_vote:
        return render(request, 'polls/poll_detail.html', context)
    else:
        results = poll.get_results_dict()
        return render(request, 'polls/poll_result.html', {'poll' : poll, 'results' : results})

@login_required
def poll_vote(request, poll_id):
    choice_id = request.POST.get('choice')
    poll = get_object_or_404(Poll, id = poll_id)
    user_can_vote = poll.user_can_vote(request.user)
    if choice_id:
        if user_can_vote:
            choice = Choice.objects.get(id = choice_id)
            new_vote = Vote(user = request.user, poll = poll, choice = choice)
            new_vote.save()
        messages.success(request, 'Your vote has been recorded!', extra_tags = 'mt-1 alert alert-success alert-dismissible fade show')
        results = poll.get_results_dict()
        return render(request, 'polls/poll_result.html', {'poll' : poll, 'results' : results})
    else:
        messages.error(request, 'Please caste your vote!', extra_tags = 'mt-1 alert alert-danger alert-dismissible fade show')
        return HttpResponseRedirect(reverse('polls:details', args=(poll_id, )))

@login_required
def add_poll(request):
    if request.method == 'POST':
        form = PollForm(request.POST)
        if form.is_valid():
            new_poll = form.save(commit = False)
            new_poll.pub_date = datetime.datetime.now()
            new_poll.owner = request.user
            new_poll.save()
            new_choice1 = Choice(
                                poll = new_poll,
                                choice_text = form.cleaned_data['choice']
                                ).save()
            new_choice2 = Choice(
                                poll = new_poll,
                                choice_text = form.cleaned_data['choice1']
                                ).save()
            new_choice3 = Choice(
                                poll = new_poll,
                                choice_text = form.cleaned_data['choice2']
                                ).save()
            messages.success(request, 'Your poll is now live!', extra_tags = 'mt-1 alert alert-success alert-dismissible fade show')
            return redirect('polls:list')
    else:
        form = PollForm()
    context = {'form' : form}
    return render(request, 'polls/poll_add.html', context)


@login_required
def add_choice(request, poll_id):
    poll = get_object_or_404(Poll, id = poll_id)
    if request.method == 'POST':
        form = ChoiceForm(request.POST)
        if form.is_valid():
            new_choice = form.save(commit = False)
            new_choice.poll = poll
            new_choice.save()
            messages.success(request, 'Choice Added Successfully!', extra_tags = 'mt-1 alert alert-success alert-dismissible fade show')
            return HttpResponseRedirect(reverse('polls:details', args=(poll_id, )))
    else:
        form = ChoiceForm()
    return render(request, 'polls/choice_add.html', {'form' : form, 'poll' : poll})

topthree/polls/templates/polls/choice_add.html
{% extends 'base.html' %}
{% block custom_title %}
  <title>Add Choice | Top Three</title>
{% endblock %}
{% block content %}

<div class="container">
  <h3 class='text-center'>{{poll.text}}</h3>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
          {{ field.errors }}
          {{ field }}
        </div>
        {% endfor %}
        <input type="submit" value="Add Choice" class='btn btn-primary'>
        <a href="{% url 'polls:details' poll.id %}" class='btn btn-primary'> Cancel</a>
        {% if edit_mode %}
          <a href="{% url 'polls:choice_confirm_delete' choice.id %}"
              class='btn btn-danger'>
              <i class="far fa-trash-alt"></i> Delete
          </a>
        {% endif %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

topthree/polls/templates/polls/poll_add.html
{% extends 'base.html' %}
  {% load static %}

  {% block custom_title %}
    <title>Add Poll | Top Three</title>
  {% endblock %}

  {% block custom_css %}
      <link rel="stylesheet" type = 'text/css' href="{% static 'css/log_styles.css' %}">
  {% endblock %}

  {% block content %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <h1 class="text-center">Add Poll</h1>
          <form action="" method="POST" class="form-signin">
            {% csrf_token %}
            {% for field in form%}
            <div class="form-group">
              {{ field.errors }}
              {{ field.label_tag }}
              {{ field }}
            </div>
            {% endfor %}
            <div class="text-center">
              <input type="submit" value="Add Poll" class="btn btn-info btn-lg">
            </div>
          </form>
        </div>
      </div>
    </div>
  {% endblock %}

topthree/polls/templates/polls/poll_detail.html
{% extends 'base.html' %}
{% block content %}
{% block custom_title %}
  <title>Poll Detail | Top Three</title>
{% endblock %}
{% if messages %}
  {% for message in messages %}
  <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
{% endif %}

  <div class="container">
    <ul>
      <div class="jumbotron mt-4">
        <h1 class="display-4"> {{poll.text}}</h1>
        <p>Asked by : <a href="{% url 'accounts:details' poll.owner %}" class="">@{{poll.owner}}</a></p>
        <form action="{% url 'polls:vote' poll.id %}" method="POST">
        {% csrf_token %}
          {% for choice in poll.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice {{forloop.counter}}">{{choice.choice_text}}</label>
            <br />
          {% endfor %}
          <a href="{% url 'polls:add_choice' poll.id %}" class="btn btn-info btn-sm">Add Choice</a>
          <hr class="my-4">
          <input type="submit" value="Vote" class="btn btn-success btn-lg">
        </form>
        </div>
    </ul>
  </div>

{% endblock %}

topthree/polls/templates/polls/poll_list.html
{% extends 'base.html' %}
{% block custom_title %}
  <title>Poll List | Top Three</title>
{% endblock %}
{% block content %}
  <div class="container">
    <h1 class="text-center">Welcome !</h1>
    <div class="list-group">
      <div class="row">
        <div class="col-sm-8 offset-sm-2">

          {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
          {% endif %}
            <a href="{%url 'polls:add'%}"class="btn btn-info my-2">Add <i class="fas fa-plus"></i></a>
             <a href="?sort-a-z=True"class="btn btn-{% if 'sort-a-z' in request.GET %}warning{% else %}primary{% endif %} my-2">A-Z <i class="fas fa-sort"></i></a>
             <a href="?votes=True"class="btn btn-{% if 'votes' in request.GET %}warning{% else %}primary{% endif %} my-2">Votes <i class="fas fa-sort"></i></a>
             <a href="?date=True"class="btn btn-{% if 'date' in request.GET %}warning{% else %}primary{% endif %} my-2">Date <i class="fas fa-sort"></i></a>
          {% for poll in polls %}
            <a href="{% url 'polls:details' poll.id %}" class="list-group-item list-group-item-action">{{ poll.text }}</a>
          {% endfor %}

          {% if polls.has_other_pages %}
          <ul class="pagination my-2">
            {% if polls.has_previous %}
             <li class="page-item">
                <li class="page-item"><a class="page-link" href="?page={{ polls.previous_page_number }}&{{params}}">&laquo;</a></li>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">&laquo;</span>
              </li>
            {% endif %}
              {% for i in polls.paginator.page_range %}
                {% if polls.number == i %}
                  <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ i }}&{{params}}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}
            {% if polls.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ polls.next_page_number }}&{{params}}">&raquo;</a></li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">&raquo;</span>
              </li>
            {% endif %}
          </ul>
        {% endif %}


        </div>
      </div>
    </div>

  </div>

{% endblock %}

topthree/polls/templates/polls/poll_result.html
{% extends 'base.html' %}

{% block custom_title %}
  <title>Poll Result | Top Three</title>
{% endblock %}
  {% block content %}

  {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
  {% endif %}

  <div class="container">
    <ul>
      <div class="jumbotron mt-4">
        <h1 class="display-4"> {{poll.text}}</h1>
        <p>Asked by : <a href="{% url 'accounts:details' poll.owner %}" class="">@{{poll.owner}}</a></p>
        <p>Total Votes : {{poll.num_of_votes}}</p>
        </div>
        {% for result in results %}
          <li>{{result.text}} - {{result.num_votes}}</li>
          <div class="progress">
            <div class="progress-bar bg-success" role="progressbar" style="width: {{result.percentage}}%;">{{result.percentage}}%</div>
          </div>
          <br />
        {% endfor %}
    </ul>
  </div>
  {% endblock %}