topthree/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('register/', views.register_user, name = 'register'),
    path('profile/<str:username>', views.details_user, name = 'details'),
    path('delete/poll/<int:poll_id>', views.delete_poll, name ='delete_poll'),
]

topthree/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('list/', views.poll_list, name = 'list'),
    path('add/', views.add_poll, name = 'add'),
    path('edit/<int:poll_id>/choice/add', views.add_choice, name = 'add_choice'),
    path('details/<int:poll_id>', views.poll_detail, name = 'details'),
    path('details/<int:poll_id>/vote', views.poll_vote, name = 'vote'),
]

topthree/topthree/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

topthree/accounts/models.py
from django.db import models

# Create your models here.

topthree/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib import messages

class UserRegistrationForm(forms.Form):
    error_css_class = 'error'

    username = forms.CharField(max_length = 100,
                               widget = forms.TextInput(attrs = {'class' : 'form-control', 'type' : 'text', 'placeholder' : 'Username:'}))

    email = forms.EmailField(widget = forms.EmailInput(attrs = {'class' : 'form-control', 'placeholder' : 'john@smith.com', 'type' : 'email', 'name' : 'email'}))

    password1 = forms.CharField(
                                max_length = 100,
                                min_length = 5,
                                label = 'Enter Password',
                                widget = forms.PasswordInput(attrs = {'class' : 'form-control', 'placeholder' : 'Enter Password', 'type' : 'password', 'autocomplete' : 'off', 'autofocus' : 'autofocus'}))

    password2 = forms.CharField(
                                max_length = 100,
                                min_length = 5,
                                label = 'Confirm Password',
                                widget = forms.PasswordInput(attrs = {'class' : 'form-control', 'placeholder' : 'Re-enter Password', 'type' : 'password', 'autocomplete' : 'off', 'autofocus' : 'autofocus'}))


    def clean_email(self):
        email = self.cleaned_data['email']
        qs = User.objects.filter(email = email)
        if qs.exists():
            # messages.success('Email is already registered.', extra_tags = 'mt-1 alert alert-success alert-dismissible fade show')
            raise ValidationError('Email is already registered.')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        qs = User.objects.filter(username = username)
        if qs.exists():
            raise ValidationError('Username already taken.')
        return username
    
    def clean_password2(self):
        p1 = self.cleaned_data['password1']
        p2 = self.cleaned_data['password2']
        if p1 and p2:
            if p1 != p2:
                raise ValidationError('Passwords Do Not Match')
        return p2

topthree/accounts/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from accounts.forms import UserRegistrationForm
from polls.models import Poll
from django.contrib.auth.decorators import login_required

# Create your views here.

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password= password)
        if user is not None:
            login(request, user)
            redirect_url = request.GET.get('next', 'home')
            return redirect(redirect_url)
        else:
            messages.error(request, 'Wrong username or password', extra_tags = 'mt-1 alert alert-danger alert-dismissible fade show')
    return render(request, 'accounts/login.html', {})

def logout_user(request):
    logout(request)
    return redirect('home')

def register_user(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            email = form.cleaned_data['email']
            user = User.objects.create_user(username, email = email, password = password)
            messages.success(request, 'User succesfully registered!', extra_tags = 'mt-1 alert alert-success alert-dismissible fade show')
            return redirect('accounts:login')
    else:
        form = UserRegistrationForm(auto_id = '%s')
    return render(request, 'accounts/register.html', {'form' : form})

@login_required
def details_user(request, username):
    user = get_object_or_404(User, username__iexact = username)
    flag = False
    if request.user.get_username() == username:
        flag = True
    print(user.poll_set.all())
    return render(request, 'accounts/details.html', {'polls' : user.poll_set.all(), 'flag' : flag, 'username' : username})

@login_required
def delete_poll(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')
    if request.method == "POST":
        poll.delete()
        messages.success(
                        request,
                        'Poll Deleted Successfully',
                        extra_tags='alert alert-success alert-dismissible fade show'
                        )
        return redirect('polls:list')
    return render(request, 'accounts/delete_poll_confirm.html', {'poll':poll})

topthree/accounts/templates/accounts/delete_poll_confirm.html
{% extends 'base.html' %}
{% block custom_title %}
  <title>Delete | Top Three</title>
{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 text-center">
      <form action="" method="post">
        {% csrf_token %}
        <input type='submit' class='btn btn-danger' value='Do you want to delete this poll?'>
      </form>
    </div>
  </div>
</div>

{% endblock %}

topthree/accounts/templates/accounts/details.html
{% extends 'base.html' %}
{% block custom_title %}
  <title>User | Top Three</title>
{% endblock %}
{% block extra_head %}
  <script src="https://kit.fontawesome.com/9304d5c7bd.js" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="text-center mt-3">Polls by {{ username }}!</h1>
    <div class="list-group">
      <div class="row">
        <div class="col-sm-8 offset-sm-2 mt-5">
          {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
          {% endif %}

          {% for poll in polls %}
            {% if flag %}
            <table class="">
              <tr>
                  <th scope="row"><a href="{% url 'accounts:delete_poll' poll.id %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a></th>
                  <td style="width: 100%"><a href="{% url 'polls:details' poll.id %}" class="list-group-item list-group-item-action">{{ poll.text }}</a></td>
              </tr>
            </table>
            {% else %}
              <a href="{% url 'polls:details' poll.id %}" class="list-group-item list-group-item-action">{{ poll.text }}</a>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>

  </div>

{% endblock %}

topthree/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block custom_title %}
    <title>Log In | Top Three</title>
{% endblock %}
{% load static %}
    {% block custom_css %}
        <link rel="stylesheet" type = 'text/css' href="{% static 'css/log_styles.css' %}">
    {% endblock %}

{% block content %}

  <form class="form-signin" method="POST" action="">
      {% csrf_token %}
      {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
      {% endif %}
      <div class="text-center mb-4">
          <img class="mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
          <h1 class="h3 mb-3 font-weight-normal">TopThree</h1>
          <p>Sign in to view, vote or see results on a poll!</a></p>
      </div>


      <div class="form-label-group">
          <input type="text" class="form-control" name="username" aria-describedby="username" placeholder="Enter username" required autofocus autocomplete="off">
          <label for="username">Username</label>
      </div>

      <div class="form-label-group">
          <input type="password" class="form-control" name="password" placeholder="Enter Password" required autocomplete="off">
          <label for="password">Password</label>
      </div>
      <div class="col-md-12 text-center">
            <button class="btn btn-lg btn-info mt-1" type="submit">Sign in</button>
            <p class="mt-2">Need an account?&nbsp<a href="{% url 'accounts:register' %}">Register Here!</a></p>
      </div>
  </form>

{% endblock %}

topthree/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block custom_title %}
  <title>Register | Top Three</title>
{% endblock %}
{% load static %}
    {% block custom_css %}
        <link rel="stylesheet" type = 'text/css' href="{% static 'css/log_styles.css' %}">
    {% endblock %}

{% block content %}

  <form class="form-signin" method="POST" action="">
      {% csrf_token %}
      {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
      {% endif %}

      <div class="text-center mb-4">
          <img class="mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
          <h1 class="h3 mb-3 font-weight-normal">TopThree</h1>
          <p>Sign up for TopThree</a></p>
      </div>
        {% for field in form%}
          <div class="form-label-group">
            {{ field.errors }}
            {{ field }}
            {{ field.label_tag }}
          </div>
        {% endfor %}

      <div class="col-md-12 text-center">
            <button class="btn btn-lg btn-info mt-1" type="submit">Register</button>
            <p class="mt-2">Already have an account?&nbsp<a href="{% url 'accounts:login' %}">Login Here!</a></a></p>
      </div>
  </form>

{% endblock %}